### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Ypot** [gizmomogwai/org-tagged#10]
Could it be possible to use colors? It could give another dimension to the board. But not sure how to determine them, maybe determined by color tags?

![imagen](https://user-images.githubusercontent.com/30699014/192368796-1d84cef9-8797-4ca2-a737-ebb97084f506.png)

Here I am using the package org-extra-emphasis: https://github.com/QiangF/org-extra-emphasis

**Comment by gizmomogwai** [comment]
I do not know at the moment how to color them in org mode / emacs.
Also its not clear how to calculate the color (especially with those nasty inherited tags) ... Its really simple to put a color tag to the parent of a tree and all children will have then at least this color + some might have another colortag applied.

**Comment by gizmomogwai** [comment]
not sure that org itself supports that.
some googling turned up: https://emacs.stackexchange.com/questions/7375/can-i-format-cells-in-an-org-mode-table-differently-depending-on-a-formula but i think this is more an emacs than an org feature.
also for exports its for sure not supported.
