### ISSUE TITLE
org-scan-tags: Symbol’s value as variable is void: org-tagged--get-data-form-heading

### ISSUE THREAD

**Issue by Ypot** [gizmomogwai/org-tagged#2]
I am getting this message, when trying to use org-tagged (C-c C-c):

`org-scan-tags: Symbol’s value as variable is void: org-tagged--get-data-form-heading`

**Comment by Ypot** [comment]
I think it was because I hadn't added rakefile.rb to my elisp path

**Comment by gizmomogwai** [comment]
no .. i think i made a typo ... get-data-form-heading does not make sense :) should be from ...
will fix in the evening! (i am in germany ...)
