### ISSUE TITLE
Implement column format

### ISSUE THREAD

**Issue by Ypot** [gizmomogwai/org-tagged#4]
I think this could be a long term issue, but I must share this idea with you.

Your initial example was:
`#+BEGIN: tagged :tags "tag1|tag2|tag3" :match "kanban"`

Could columns be controlled near as they can be controlled in [column-view](https://orgmode.org/manual/Column-attributes.html)?:

An example could be:
`#+BEGIN: tagged :tags "%25tag1(Column 1)|tag2|tag3" :match "kanban"`
Where the first column would have a max width of 25 characters and its title would be "Column 1".

**Comment by gizmomogwai** [comment]
Yes ... this could be an option for the format string ... not sure if we want to have them together though. 
e.g. in org-kanban i have the `:layout` parameter that specifies it. But I like your idea of having it all together. Makes sense and in org-tagged we also have to specify the alternative title (arguably, because the tag could also be a nice named one), and the length. . only question is, what todo with things that are too long .. just cut them, or somethow add `...` at the end?

**Comment by gizmomogwai** [comment]
I also would then rename the atom .. .from `:tags` to `:columns` or something.

**Comment by gizmomogwai** [comment]
@Ypot please see the file `features/data/test1.org` for an example.

**Comment by Ypot** [comment]
Tried, it seems something broke:
`s-split: Wrong type argument: stringp, nil`

**Comment by Ypot** [comment]
EDIT: Bug confirmed, it won't work.


> . . only question is, what todo with things that are too long .. just cut them, or somethow add `...` at the end?

Not sure!!! It doesn't work right now for me, maybe I found a bug. 
This should work for you to test it:

```
** Top node for columns view
      :PROPERTIES:
      :COLUMNS: %5ITEM(TITLE)
      :END:

#+BEGIN: columnview :hlines 1 :id local
#+END:
```


And this should work too:
```
 #+COLUMNS: %5ITEM(TITLE)

  ** Top node for columns view

#+BEGIN: columnview :hlines 1 :id local
#+END:
```

**Comment by Ypot** [comment]
> @Ypot please see the file `features/data/test1.org` for an example.

It works great!

Although with my real headlines I am having issues (very weird behavior, I can't "debug" it).

**Comment by Ypot** [comment]
See:

https://www.tiktok.com/@yporg/video/7146738419857706246?is_from_webapp=1&sender_device=pc&web_id=7100507416085399046

**Comment by gizmomogwai** [comment]
mhh ,., i was trying to reproduce this, but failed (for now).
can you get the newest version c50bc1b96b050b37620b46c9dfd3860e2d372c8d and eval the whole buffer and then try again?
also :match should be on a tag (not sure that this is a problem, but also not sure, that `*` is a valid org mode match expression).
another annotation is:
the format for the columns is different from columns view: in columns view one selects what from a item is shown in the column (we always show the heading) and in tagged we select the tag, its replacement and length.

please reopen if you have tested with the newest version.

**Comment by gizmomogwai** [comment]
one bug i get is, if there is an item selected, that does not have any tag of the tayble, an empty table row is produced, which is not helpful! ... will fix that!

**Comment by gizmomogwai** [comment]
see #5
