### ISSUE TITLE
stringp violation when an element is not really tagged

### ISSUE THREAD

**Issue by Ypot** [gizmomogwai/org-tagged#6]
Testing with the new 0.0.3 version.
It works great on the test.org you created :D 

But my org-mode text must be quite weird, because org-tagged doesn't work on it.
If you want to, I could share it, but it has some personal data on it.

**Comment by gizmomogwai** [comment]
Any file that does not work and you can share helps. Otherwise Ou can delete the 2nd half of your file and see if it still is broken or works ... And continue b halving ... Should be quite fast to find the perpetrator;)

**Comment by gizmomogwai** [comment]
If you don't mind you can also send me the file by email and I narrow it down. Will not share it!

**Comment by gizmomogwai** [comment]
How big is the file? You could also replace all headings with test1 ..1000 and send me ;)

**Comment by Ypot** [comment]
> Any file that does not work and you can share helps. Otherwise Ou can delete the 2nd half of your file and see if it still is broken or works ... And continue b halving ... Should be quite fast to find the perpetrator;)

That I did yesterday, do you remember the video I shared? Something was wrong.

I will share the file with you.

**Comment by gizmomogwai** [comment]
Is yesterdays example still wrong for you?
thats surprising ... 
unfortunately i am very sorry, that the library works so bad for you, but we will get there i think.

**Comment by gizmomogwai** [comment]
```
* test1 :kanban:
** test2
```
delivers test1 and test2 in `org-map-entries ... "kanban"` (although it should imho only deliver test1)

further
```
* test1 :kanban:
** test2 :tag1:
```
will fill in a table with `:columns "tag1" :match "kanban"`.... not sure if this is a problem though.

i also do not want to implement my own org-map-entries ...
