### ISSUE TITLE
Make truncation string configurable

### ISSUE THREAD

**Issue by Ypot** [gizmomogwai/org-tagged#7]
Sorry, I know you asked me several times, but I wasn't sure. Now I think that adding `...` at the end of the items, could be too long?
Maybe it would be better a single character?

What do you think about the arrow emacs uses by default for long lines?

I think it is this symbol (not sure), in the bottom I show you an example:

`             to input: type "C-x 8 RET 2192" or "C-x 8 RET RIGHTWARDS ARROW"`

```
            character: → (displayed as →) (codepoint 8594, #o20622, #x2192)
              charset: unicode (Unicode (ISO10646))
code point in charset: 0x2192
```

```
  name: RIGHTWARDS ARROW
  old-name: RIGHT ARROW
  general-category: Sm (Symbol, Math)
  decomposition: (8594) ('→')
```

![imagen](https://user-images.githubusercontent.com/30699014/192120443-6a73364c-d888-4c6c-8a39-742cf4895f7a.png)
https://www.emacswiki.org/emacs/TruncateLines

**Comment by gizmomogwai** [comment]
nice idea i would say .. in org-kanban i think i am fallbacking to ellipsis (…) which is one unicode for three dots ...
also in org-kanban its all configurable through customizable variables that could be made dir-local and so on ... should also be an option in the dynamic block header ...
