### ISSUE TITLE
Include inherited tags when calculating the tagged table

### ISSUE THREAD

**Issue by gizmomogwai** [gizmomogwai/org-tagged#8]
@Ypot would you expect `Tree` and `Subtree` in the table in this example
```
* Tree :kanban:tag1:
** Subtree

#+BEGIN: tagged :columns "tag" :match "kanban"
#+END:
```
or just `Tree`?

**Comment by Ypot** [comment]
Just "Tree".

Less aggressive, and non exclusive. It allows more flexibility, and you always could :match "{.}" or add the tag to the subtrees.

**Comment by gizmomogwai** [comment]
the match is not the problem. (actually that was the rootcause for the bug you reported). i think now it should be included (as it then would behave consistent with e.g. org agenda). perhaps an option to not include it ...

**Comment by Ypot** [comment]
Is it possible to generate a kanban table wich shows the state of just the Projects (without tasks' "noise")?

```
* Project 1                                                           :doing:prj:
** task 1          :doing:
** task 2          :doing:
** task 3          :doing:
 
* Project 2 :backlog:prj:
** task 4  :backlog:
** task 5  :backlog:
** task 6  :backlog:
 
#+BEGIN: tagged :columns "%25doing|backlog" :truncation-string " >"
| doing     | backlog   |
|-----------+-----------|
| Project 1 |           |
|           | Project 2 |
#+END:
```

**Comment by Ypot** [comment]
> Is it possible to generate a kanban table wich shows the state of just the Projects (without tasks' "noise")?
> 
> ```
> * Project 1                                                           :doing:prj:
> ** task 1          :doing:
> ** task 2          :doing:
> ** task 3          :doing:
>  
> * Project 2 :backlog:prj:
> ** task 4  :backlog:
> ** task 5  :backlog:
> ** task 6  :backlog:
>  
> #+BEGIN: tagged :columns "%25doing|backlog" :truncation-string " >"
> | doing     | backlog   |
> |-----------+-----------|
> | Project 1 |           |
> |           | Project 2 |
> #+END:
> ```

SOLVED:
I've excluded :prj: tag from inheritance. I could've too voided tags inheritance:
```
Org Use Tag Inheritance
Org Tags Exclude From Inheritance
```

**Comment by gizmomogwai** [comment]
Nice .. I did not know of tag inheritance before this project ... Does not make 100% sense to me. I wonder if there is a match on heading level, so that one can only include top level headings

**Comment by gizmomogwai** [comment]
I think we need to go back on this one.
The problem is, the :match expression behaves differently from what we do if :inherit-tags is nil.
My suggestion would be to drop the :inherit-tags option and always work with all (also inherited) tags as the builtin :match is doing.

To solve your above problem: Instead of using a global option (that might make problems with other org features e.g. agenda) to enable/disable inherited tags its better imho to select exactly the elements that should be looked for. something like `:match "kanban&LEVEL\<2"`.

what do you think ? i would remove the (inconsistent and broken) support for local tags and we can work with better :match selections?

**Comment by Ypot** [comment]
> I think we need to go back on this one. The problem is, the :match expression behaves differently from what we do if :inherit-tags is nil. My suggestion would be to drop the :inherit-tags option and always work with all (also inherited) tags as the builtin :match is doing.
> 
> To solve your above problem: Instead of using a global option (that might make problems with other org features e.g. agenda) to enable/disable inherited tags its better imho to select exactly the elements that should be looked for. something like `:match "kanban&LEVEL\<2"`.
> 
> what do you think ? i would remove the (inconsistent and broken) support for local tags and we can work with better :match selections?

More modular selection seems to be a luxury, if you think it is affordable, it would be great.
Although I think you should share some test.org to speak the same language, I am not grasping 100% of it.

**Comment by gizmomogwai** [comment]
Good idea, will add another test file that replicates and hopefully solves you problem

**Comment by gizmomogwai** [comment]
@Ypot please see https://github.com/gizmomogwai/org-tagged/blob/94c5bbb4bda0625d139ec37a7a8d826b2edee6de/features/data/test-proj.org for an example.
I hope that works for you as well!

**Comment by Ypot** [comment]
Today I have no PC at home. Give me a couple of days.

**Comment by Ypot** [comment]
Tags are always inherited independently of the emacs configuration?
"&level" feature works well :-)

I think I should use it some time to have a say about it :m  

Good job in any case :-)

**Comment by Ypot** [comment]
Oh, I hadn't seen that it says "Task x in Project Y"
Great!

**Comment by Ypot** [comment]
> Oh, I hadn't seen that it says "Task x in Project Y" Great!

Me wrong, I editted the headline and I didn't see it already was written in the headline. Nonsense, sorry.
